name = "TestPackage"
uuid = "5054dc4c-b8be-49c7-bb13-1164454da54d"
authors = ["Marck Llerena"]
version = "1.0.0-DEV"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"


[compat]
ForwardDiff = "0.10.38"
SafeTestsets = "0.1.0"
julia = "1.11.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[targets]
test = ["Test", "SafeTestsets"]
