name = "TestPackage"
uuid = "5054dc4c-b8be-49c7-bb13-1164454da54d"
authors = ["Marck Llerena"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
